#pragma once

#define THERMOSTAT_ENABLE_GPIO_PORT GPIO_PORT_B
#define THERMOSTAT_ENABLE_GPIO_PIN 5

#define TEMP_SENSOR_GPIO_PORT GPIO_PORT_A
#define TEMP_SENSOR_GPIO_PIN 0

#define BUTTON_KEY_LEFT_PORT B
#define BUTTON_KEY_MID_PORT B
#define BUTTON_KEY_RIGHT_PORT B
#define BUTTON_KEY_LEFT_PIN 9
#define BUTTON_KEY_MID_PIN 5
#define BUTTON_KEY_RIGHT_PIN 8

/* Debug pin */
#define DEBUG_PIN_PIN 13
#define DEBUG_PIN_PORT C
