#pragma once

#define TEMP_SENSOR_GPIO_PORT GPIO_PORT_A
#define TEMP_SENSOR_GPIO_PIN 0

#define PUMP_ENABLE_GPIO_PORT GPIO_PORT_A
#define PUMP_ENABLE_GPIO_PIN 10

#define THERMOSTAT_ENABLE_GPIO_PORT GPIO_PORT_B
#define THERMOSTAT_ENABLE_GPIO_PIN 5

#define BUTTON_KEY_MAIN_GPIO_PORT GPIO_PORT_B
#define BUTTON_KEY_MAIN_GPIO_PIN 9

#define DEBUG_PIN_GPIO_PORT GPIO_PORT_C
#define DEBUG_PIN_GPIO_PIN 13

#define DISPLAY_SH1106_CS_GPIO_PORT GPIO_PORT_A
#define DISPLAY_SH1106_CS_GPIO_PIN 4

#define DISPLAY_SH1106_RST_GPIO_PORT GPIO_PORT_A
#define DISPLAY_SH1106_RST_GPIO_PIN 6

#define DISPLAY_SH1106_DC_GPIO_PORT GPIO_PORT_B
#define DISPLAY_SH1106_DC_GPIO_PIN 0

#define SPI_NSS_GPIO_PORT GPIO_PORT_A
#define SPI_NSS_GPIO_PIN 4

#define SPI_SCK_GPIO_PORT GPIO_PORT_A
#define SPI_SCK_GPIO_PIN 5

#define SPI_MOSI_GPIO_PORT GPIO_PORT_A
#define SPI_MOSI_GPIO_PIN 7

#define SWDIO_GPIO_PORT GPIO_PORT_A
#define SWDIO_GPIO_PIN 13

#define SWCLK_GPIO_PORT GPIO_PORT_A
#define SWCLK_GPIO_PIN 14

#define FLOW_METER_GPIO_PORT GPIO_PORT_B
#define FLOW_METER_GPIO_PIN 12

#define I2C1_SDA_PORT GPIO_PORT_B
#define I2C1_SDA_PIN_6 6

#define I2C1_SCL_PORT GPIO_PORT_B
#define I2C1_SCL_PIN_7 7
