#pragma once

#define TEMP_SENSOR_GPIO_PORT GPIO_PORT_A
#define TEMP_SENSOR_GPIO_PIN 0

#define PUMP_ENABLE_GPIO_PORT GPIO_PORT_A
#define PUMP_ENABLE_GPIO_PIN 10

#define THERMOSTAT_ENABLE_GPIO_PORT GPIO_PORT_B
#define THERMOSTAT_ENABLE_GPIO_PIN 5

#define BUTTON_KEY_MAIN_GPIO_PORT GPIO_PORT_B
#define BUTTON_KEY_MAIN_GPIO_PIN 9

#define DEBUG_PIN_GPIO_PORT GPIO_PORT_C
#define DEBUG_PIN_GPIO_PIN 13

#define DISPLAY_SH1106_CS_GPIO_PORT GPIO_PORT_A
#define DISPLAY_SH1106_CS_GPIO_PIN 4

#define DISPLAY_SH1106_RST_GPIO_PORT GPIO_PORT_A
#define DISPLAY_SH1106_RST_GPIO_PIN 6

#define DISPLAY_SH1106_DC_GPIO_PORT GPIO_PORT_B
#define DISPLAY_SH1106_DC_GPIO_PIN 0

